name: download-ndk-release

on:
  workflow_dispatch:

jobs:
  download-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Download NDK
        run: |
          wget -O android-ndk-r17c-linux-x86_64.zip \
          https://dl.google.com/android/repository/android-ndk-r17c-linux-x86_64.zip

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: "ndk-r17c-${{ github.run_number }}"
          name: "NDK r17c #${{ github.run_number }}"
          artifacts: "android-ndk-r17c-linux-x86_64.zip"
          draft: false
          prerelease: false
